# import week1
# import week2
import week3

# print(week1.PatternStart('CGC','ATGACTTCGCTGTTACGCGC'))
# print(week2.RevComp('GCTAGCT'))
# print(week2.Skew('CATGGGCATCGGCCATACGCC'))
# print(week2.Skew('TAAAGACTGCCGAGAGGCCAACACGAGTGCTAGAACGAGGGGCGTAAACGCGGGTCCGAT'))
# print(week2.MinSkewPos('TAAAGACTGCCGAGAGGCCAACACGAGTGCTAGAACGAGGGGCGTAAACGCGGGTCCGAT'))

# print(week2.HammingDistance('GGGCCGTTGGT','GGACCGTTGAC'))
# print(week2.ImmediateNeighbors('ACG'))
# print(week2.Neighbors('ACG',1))
# print(week2.Neighbors('GTGCACATCAAT',2))
# print(week2.AproximatePatternCount('GAGG','TTTAGAGCCTTCAGAGG',2))
# print(week2.FrequentWordsWithMismatches('ACGTTGCATGTCGCATGATGCATGAGAGCT',4,1))
# print(week2.FrequentWordsWithMismatchesRevcomp('ACGTTGCATGTCGCATGATGCATGAGAGCT',4,1))
# print(week2.FrequentWordsWithMismatchesRevcomp('AAAAAAAAAAAA',2,1))

# Quiz-week2
# print(week2.HammingDistance('CTTGAAGTGGACCTCTAGTTCCTCTACAAAGAACAGGTTGACCTGTCGCGAAG','ATGCCTTACCTAGATGCAATGACGGACGTATTCCTTTTGCCTCAACGGCTCCT'))
# print(week2.MinSkewPos('GATACACTTCCCGAGTAGGTACTG'))
# print(week2.AproximatePatternCount('TGT','CGTGACAGTGTATGGGCATCTTT',1))
# print(len(week2.Neighbors('ACGT',3)))
# print(week3.MotifEnumeration(['ATTTGGC','TGCCTTA','CGGTATC','GAAAATT'],3,1))
# print(week3.MotifEnumeration(['ATCACCCGGTTCCACTATTTATGAT','ATGCTTGGTACATCGTCTACCGATG','ACGAGATGGTCGGATAGTTAACTAT','CGTGGCATCCCACGGATGCTCATAG','TGGCAATCCACCGGAATGATGTCGG','TCTCGGTTCGATGTTGGTTGTTGTA'],5,1))

# print(week3.calcEntropy([0.25,0.25,0.25,0.25]))
# print(week3.calcEntropy([1]))
# print(week3.MotifEntropy(["TCGGGGGTTTTT", "CCGGTGACTTAC", "ACGGGGATTTTC", "TTGGGGACTTTT", "AAGGGGACTTCC", "TTGGGGACTTCC", "TCGGGGATTCAT", "TCGGGGATTCCT", "TAGGGGAACTAC", "TCGGGTATAACC"]))
# print(week3.DistanceBetweenPatternAndStrings('AAA', ['TTACCTTAAC',  'GATATCTGTC', 'ACGGCGTTCG', 'CCCTAAAGAG', 'CGTCAGAGGT']))
# print(week3.MedianString('AAATTGACGCAT GACGACCACGTT CGTCAGCGCCTG GCTGAGCACCGG AGTTCGGGACAG',3))
# print(week3.MedianString('TCTCCACACCCTGCAACACCTCTTTCATCAAAGTGGTAGAAC CCTTCTGGGATGGCTTTAATAGTAGTTGGCTTATCACAATTC CTCACAAGTGGTGAGACATCATCACGTAAATCTGGTAAATCC GTAAAGCCATGTTTACATGGCTAGTGATCAGTCACTGATTAT CCCGACTTGCGTTGATCATTCATGTCAAGTACCGGTTGATTG TCTGTATCCGTTCGTTACTCATCACGATGCGATAAATTATGC CGGGGAAACTCCCGCTTCGCTTGGCTGCGGTATCGTTCATCA GTTGACGCTTTATAGGGTTAAGAGCATGTGTGATCACGGGGT GCTACGGGACCCCCCTCAATAGTGTTCTTCCTACACTCATCA TGCTGGGGGGGGGCGGCCGAGTCCTCATCATGGGTAGTCTGA',6))
# print(week3.MotifProbability('ACGGGGATTACC',{'A': [0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.9, 0.1, 0.1, 0.1, 0.3, 0.0],'C': [0.1, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.1, 0.2, 0.4, 0.6], 'G': [0.0, 0.0, 1.0, 1.0, 0.9, 0.9, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0], 'T': [0.7, 0.2, 0.0, 0.0, 0.1, 0.1, 0.0, 0.5, 0.8, 0.7, 0.3, 0.4]}))
# print(week3.MostProbableKmer('ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT',5,{
#     'A': [0.2, 0.2, 0.3, 0.2, 0.3],
#     'C': [0.4, 0.3, 0.1, 0.5, 0.1],
#     'G': [0.3, 0.3, 0.5, 0.2, 0.4],
#     'T': [0.1, 0.2, 0.1, 0.1, 0.2]
# }))
# print(week3.MostProbableKmer('ACGACATCACCAGATCCACTGAGGCTCCATTGCTATTGGCTTGGGTCCGTTGCTGACGGACAATTTTTAGAAGGATCCCTTACCACAGCACGCATCACAGGCCAATGCCCATGCCGCATACTGGACTACTGGAAGTCAACATAACTGGAGTGCAGGCCTACGGCAACCAACGGACAGTAGGACTGGTAGCATAGATATAAGACACTCTGGACTTTCTGTTAGGAAGAGATTGTATTCTAGTTTCCATTCGTGTCATAAGCTATGTACGCCGCAGTGAGTACTGAGGCCGTAGCTAAGTGTGATCGAGATGGACTCGAACAGACCTCGTATGGCTTGTAATAGTCCCATACGCGGAATAGCACAACTCTGAGTAAAAACCTCTCCTGATAGTACTATCGGTAGTTAAGAGCTCGTATCTTGGGAACCCCACCCTCTTTAATGCCATTGCCAACTAGAATCGCAGATGGGCGCAGCTCTACTACCGGCTGACGACGTCTACCACGGATTCGTCGGCTTGGCCCCCGATGTCGACGGTAGACCGCACGGGAGAGTCTTCTGTGTCCTTTGTGGCGATTTCTGTAGGTGCACTAGCCTCGAACGCTAATTGCTCTTGTTTGATGCATTGATCAGATGTTACTGACAGCCGCGACCGACACGCCTCACGATGCTCAGGCTACGGCATGAATGAGTAGCCGGAAAGATAGATATTGTTTCAAGGGTATAATTAGGAGGTTGCTTGGTTCACGTAATATCCACGAGCGCCGTAGAGGCAATTGGGTCATGTTAAAGCCCCGCAGCATGAAGTCTTACTCCCACGCTGTGTTTGGGCTCCGCGCGATGCTGCTAGTAATCTTCAGCTTTGGGTCCATGGGGTTAGGTAACTGGTACCAGCTTCGAACCTTATACTGAAATGCTAGCCGAATCCAATGATCCCTGCCAAAAACCCTTGCGGTATGTTCGTGCCATCCATGCTGTTCCCAAGATTTAGGAGCTACGCGTG',13,{'A': [0.289, 0.289, 0.171, 0.197, 0.303, 0.211, 0.184, 0.184, 0.289, 0.329, 0.276, 0.25, 0.224], 'C': [0.329, 0.303, 0.197, 0.237, 0.211, 0.237, 0.329, 0.289, 0.276, 0.289, 0.158, 0.224, 0.263], 'G': [0.25, 0.197, 0.395, 0.342, 0.316, 0.25, 0.197, 0.211, 0.211, 0.171, 0.303, 0.289, 0.342], 'T': [0.132, 0.211, 0.237, 0.224, 0.171, 0.303, 0.289, 0.316, 0.224, 0.211, 0.263, 0.237, 0.171]}))
# print(week3.GreedyMotifSearch('GGCGTTCAGGCA AAGAATCAGTCA CAAGGAGTTCGC CACGTCAATCAC CAATAATATTCG',3,5))
# print(week3.GreedyMotifSearch('GCCCAA GGCCTG AACCTA TTCCTT',3,4))
# print(week3.GreedyMotifSearch('GAGGCGCACATCATTATCGATAACGATTCGCCGCATTGCC TCATCGAATCCGATAACTGACACCTGCTCTGGCACCGCTC TCGGCGGTATAGCCAGAAAGCGTAGTGCCAATAATTTCCT GAGTCGTGGTGAAGTGTGGGTTATGGGGAAAGGCAGACTG GACGGCAACTACGGTTACAACGCAGCAACCGAAGAATATT TCTGTTGTTGCTAACACCGTTAAAGGCGGCGACGGCAACT AAGCGGCCAACGTAGGCGCGGCTTGGCATCTCGGTGTGTG AATTGAAAGGCGCATCTTACTCTTTTCGCTTTCAAAAAAA',5,8))
# print(week3.GreedyMotifSearch('GCAGGTTAATACCGCGGATCAGCTGAGAAACCGGAATGTGCGT CCTGCATGCCCGGTTTGAGGAACATCAGCGAAGAACTGTGCGT GCGCCAGTAACCCGTGCCAGTCAGGTTAATGGCAGTAACATTT AACCCGTGCCAGTCAGGTTAATGGCAGTAACATTTATGCCTTC ATGCCTTCCGCGCCAATTGTTCGTATCGTCGCCACTTCGAGTG',6,5))
# print(week3.GreedyMotifSearch('GATGGACCGGGCCATACATGGTGACACGCATCAGAAAGCTGTCCCCGTGCCTTATGCGCTGTCTGTTAGTACATCTCTCTCAATGGCCGTATTTTCAGAACAAGTATCACTTGGATCATCATCTACTCGACGGAGGGCGCGCAAGTGGGTATCTCG TAAAAAGGTATAAGGGAGTCATATCCGCAGTCCTAGTGACCTTTCCCGGCCCTAGCAGTGCTCCGATAGCCCATGGATGAGACGTAACTCGGCTACTGTTTGTGACTCAAGATAGTTGCCGTCGATATCTCGGATTCTGCTTATCGTGTTACGAGC AACCACGAGTACCTCTGTCGTGGTCCTTCACCAGGACTCGAAATTTGGCTCACGCCCAACGCCAAGATTACGTCGATCGTTCCTGTTGATATCTCGCCGCATATCAGGTTTATACTGATCGGCTCAGTGATTGTTAATCATCGGCGCGGGTTGTCA TGTCATGTGCGGATACAGTGGTGACACCAGGTCACCTCCGACCTAAAAGCGTTCAAGGTATGGCCCGAAGAGGTAGGTATCTCTTGTGCCCGCTGCTGCTATCACTCCCTGTGAGCCCCGACACGAATGTTAAACCAGTTTATATTCGCTCGTCAT AACCTAAACCCTTGCTTCCCACCATCCCTGCGAAGCAACCTTATCCGTAGTTCAGTCGCGCTGAACTCGGAAAGTGCGCTCACGAGATTCTAACTTACACTTGTTTAAGTACCACGTCCGGTGGATATCGCTGGCGTTGAAGGATAGTTCTGGTTA GTGCCCGATATGCCCGTCAGGGTTGAAGTCTGGGAAGTCGTTATCCCAAACGAAATACCCCGTTCGCAGGCGTGATGTATATCCTGATTAGTACCGCGTATAATATTAGTTTCGCACAGGAGCGTGCTTGTTTTGGGTCATGGATTGGGTACAGCA TAGTCTTCGAGGCATCTACCTGCGACCGAGCTTGCGATCCAAAAGCATACCCATGAAGTTTGCAAATCTTTCTTAGAGCTACAGGTAGATATCCCTGGGCCGGTAACTAGTAATATGTACAGTTTAGTTGTCCTGTACAATACTGATTGGAGTCAG AGGAGACGTGTTTGGTAGGCGCTCGACCCTTACCCCCCTATCTCGACTGGCATTGGACGTCCTCAGACTGGTGGATTTGACCTAGTGGTTATCACGCACATGGGAGAACCCGGTCAGAATACATCCTGTTACAGTCAGACGCCGGGTCATTCGCAA TGTGGGGATCGTCTGATTCATCGACGTCATGGAAACGGGGACGGGCCAGTGGTTATCCCATGCTGCCTTTTAGGAATTCTAGGAGGCGTTCCTAAATAGCTCGCCCGACGATATCCTACTTGATTGTGGCGGTATACCTTGCTGAACCTCGCAGTA CGCAGTGCACTAGTGGCTATCGCCTTTCTATCCCTGAGGCGTTTGCGTTATAAGATCACTCTGTCGGTGTGAAACCACTGAGTCACACTGACCGGTCGACTGGCCCGTCATATGCAAGTTGAAACGCTTACTGCCGGGTATCGCTCTAAGCTCGAC TACTCGTAACTTCAAAATCTCGTAGGGTCTGCAGAGTAAGAATCCCGGATACTTCAACATTATCGATTCGTCAAGACGTGCGGAGTGGATATCCCTTATTCCTATACGTCACAAGCCGCGGTCAAGTCGCTTACGCACGGTAGAGCGGGAAACCCT GCTCTAGTACGCCACAGTGCCAGTACATGACCTCACGAGCCGCCACTTACGTTGATATGTTATAAATCACTAGTTTCGTTGGTACAAACAATAAGTGAGAAGCAATGAGCAACTTATCTCATAAAAAGTGTGGTCGTTATCACACATGACATAAAC GAGACGGTCGTAGAAATTTGCGCTTGCTCGTATCTCAGTATCCTTCAAAGATTGAACCGGATCGCGGCGGCTAATATTGAAATCCTTAGACTTAACGTTGGTATCACTTTAGAATTTCTGACTTGAGGGTAGTGACTAGACAATCATGATGGAAGA GATCGGTGGCAGTTGAATTAAGACTAGTTATCCCCTGCTTACACTTTTTCCGCCCGGACACGTGTGACGGTAGTTGATATCTCTCAAGTATCCCGACTTCACGTACGATGCCACCCATCTCCGGCAAACACACTTCTATAATATCGTGGAGCCGAA GTAGGTATCACCAGAGTTCTCTCGGTATGTGGCGCTAAAACCTCTTAGAGTATGAAGGGTGAAGACCAAGCTCATACCACCCCTATATAGGGCTAATTAATTCCACATCCAGGCAAGATGTCACCCTACAGGTCGCTCACTTGTGGAGAACATCAC GTGGCTATCGCTGTGATCCGTCACACAAAATCAACTTTGTAGTATTTTGGGTAGTCGGGATAACGCGTGGTCTAAGGTGAGCTGCCTTTGATCCGTTGGGTGGCTACCTTGCAAGTTACCGGCTTGTCACTAGATATAACCGGAAGTCTCTGCAAA TGAGCAGACCCGACAAAGGCCATGACTTCAAAACCGGTTGTGCAGCGACAGGTACTTTAAGTACGGCACCATTAATATCGCTATACTTACGAGTTAGTGGGTATCTCATGCAAACAAACTGCTACTAGGAACTTAGACGAACTTACCAGGAGGATT AGTGATCTGAGCATAGTATACTGAGAACGTGTGTGTGACCCCTCCAGCGTCCCCGGCTACTGTTCCAGATCCTAACTAATTACTGCTAGCGATCTGGTCGATATCGCTACGGAACGAAGCCGTACAATCGCCCAGAAGCGGTTAGTCAAGGGCGTT CAAAATGGGAGTACTTCTCGTAGAATAATTCGTCTGTAATTCCTAGGTTCCATAGATAGGCCTCGATAGTGAAATTCCTTCATGCCCCGAGGTGGCGTTGATATCTCCTTTCTAAGCGGTACCCTTAAGAGTACTCGCGATGGGCTTATCCTCCTC GTTGGTATCACCCCCAATCCTCTTAGTTTACACTGTAAGATTAACGTCAGGGTGTTGTGGATGGCTTTTCTAATTTAGGTCCTCGGGATGCTCAGGTGTTACTATCGGACTGAGTGAATGTAAGTCCGGGTATCAGCCATGAAACCACTGGAGATC CCTCGGAAAACGTCGTAAGTGGTATCACAATCCACTAGTCACGGAGGGCGGTGAGTGTCTCGATGCTCAACCCCCAACCCTCAGATGAGGCTATCTGTAGGTATCACTTACGTCACTACGGGGAACAGCTCGCCTTAAGTGTAGGCTAGGTATATG GGCGGCTCCATCCGATGTGACGGATTTCATGAGGCACAAGCGCTTCACTCCCTATTTGGCTCGTGACAAAGTTCAACGGCTTTGCAGATATCCATGGTCGTTATCCCGGTGGTGAACCTACCGTCAAGTCTCTACAGTGCGCGAAGTGTCCCGGGC TACTAGTATAAGTTCCGAGCCAAATGGATGGCCCAGGCGCACTAGTGTTAGAAGGATTCGGGCTGTAGGTACATCAAGCTCGAATTTGTCCCACGTCATTCTGGGCCACCCGGACCACAGAAGACCTCTCTCTGTGCCGACGGTGTGGTTATCACG GTGGTTATCACCGGGATCGAATACAGATACGTCTGGTACATGCCTTGTCATTATTCATACGCCCCCTGGGCCAACAATCCTTTGTCAACCGCGGTCAAAAAGGTAACTAGGATCGGCTTGATCTCTAATTCCGGACTGTTCACCACGGGTCGACCG CATCACGCAATGCGAACGACTGAAGAAGGCAAGGACAGTTACGCAACCTATCATGCGTAGATCAAGGTAATCGGGACCGGTCTGGAATTTAGGAGTGTTGTTATCGCAACCTGCGATCATAACATCCTCTTATTGCCTATAAACCGACCCTGACCG',12,25))
print(week3.GreedyMotifSearch('GACCTACGGTTACAACGCAGCAACCGAAGAATATTGGCAA TCATTATCGATAACGATTCGCCGGAGGCCATTGCCGCACA GGAGTCTGGTGAAGTGTGGGTTATGGGGCAGACTGGGAAA GAATCCGATAACTGACACCTGCTCTGGCACCGCTCTCATC AAGCGCGTAGGCGCGGCTTGGCATCTCGGTGTGTGGCCAA AATTGAAAGGCGCATCTTACTCTTTTCGCTTAAAATCAAA GGTATAGCCAGAAAGCGTAGTTAATTTCGGCTCCTGCCAA TCTGTTGTTGCTAACACCGTTAAAGGCGGCGACGGCAACT', 5,8))

